from rest_framework import routers
from django.urls import path

from .api_views import (
	AITripBuilderPreviewAPIView,
	AITripBuilderSelectAPIView,
	CheckoutRequestCreateAPIView,
	CheckoutRequestStatusAPIView,
	ConsultancyProfileAPIView,
	DashboardAPIView,
	DocumentTripCreateAPIView,
	EngagementTrackAPIView,
	HomeAPIView,
	LeaderboardAPIView,
	LoginAPIView,
	MessageSummaryAPIView,
	MessageThreadDetailAPIView,
	MessageThreadListAPIView,
	MembershipBillingPortalAPIView,
	MembershipCancelRecurringAPIView,
	MemberDirectoryAPIView,
	LogoutAPIView,
	OperationsActivateCheckoutAPIView,
	OperationsOverviewAPIView,
	SessionAPIView,
	SignupAPIView,
	StripeCheckoutSessionAPIView,
	StripeWebhookAPIView,
	TripViewSet,
)

router = routers.DefaultRouter()
router.register(r'trips', TripViewSet)

urlpatterns = [
	path('auth/signup/', SignupAPIView.as_view(), name='api-auth-signup'),
	path('auth/login/', LoginAPIView.as_view(), name='api-auth-login'),
	path('auth/logout/', LogoutAPIView.as_view(), name='api-auth-logout'),
	path('auth/session/', SessionAPIView.as_view(), name='api-auth-session'),
	path('checkout/request/', CheckoutRequestCreateAPIView.as_view(), name='api-checkout-request'),
	path('checkout/request/<str:reference>/', CheckoutRequestStatusAPIView.as_view(), name='api-checkout-request-status'),
	path('membership/recurring/portal/', MembershipBillingPortalAPIView.as_view(), name='api-membership-billing-portal'),
	path('membership/recurring/cancel/', MembershipCancelRecurringAPIView.as_view(), name='api-membership-cancel-recurring'),
	path('checkout/stripe/session/', StripeCheckoutSessionAPIView.as_view(), name='api-checkout-stripe-session'),
	path('checkout/stripe/webhook/', StripeWebhookAPIView.as_view(), name='api-checkout-stripe-webhook'),
	path('engagement/track/', EngagementTrackAPIView.as_view(), name='api-engagement-track'),
	path('operations/overview/', OperationsOverviewAPIView.as_view(), name='api-operations-overview'),
	path('operations/checkout/<str:reference>/activate/', OperationsActivateCheckoutAPIView.as_view(), name='api-operations-activate-checkout'),
	path('home/', HomeAPIView.as_view(), name='api-home'),
	path('members/', MemberDirectoryAPIView.as_view(), name='api-members'),
	path('messages/summary/', MessageSummaryAPIView.as_view(), name='api-message-summary'),
	path('messages/threads/', MessageThreadListAPIView.as_view(), name='api-message-threads'),
	path('messages/thread/<int:user_id>/', MessageThreadDetailAPIView.as_view(), name='api-message-thread-detail'),
	path('leaderboard/', LeaderboardAPIView.as_view(), name='api-leaderboard'),
	path('dashboard/', DashboardAPIView.as_view(), name='api-dashboard'),
	path('profile/consultancy/', ConsultancyProfileAPIView.as_view(), name='api-profile-consultancy'),
	path('trips/document/', DocumentTripCreateAPIView.as_view(), name='api-trip-document'),
	path('ai-trip-builder/preview/', AITripBuilderPreviewAPIView.as_view(), name='api-ai-trip-builder-preview'),
	path('ai-trip-builder/select/', AITripBuilderSelectAPIView.as_view(), name='api-ai-trip-builder-select'),
] + router.urls
