# Generated by Django 6.0.3 on 2026-03-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='author_metric',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='expert',
            name='consultancy_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='consultancy_mode',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='expert',
            name='consultation_rate',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='expert',
            name='countries_visited',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expert',
            name='initials',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='expert',
            name='is_dashboard_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expert',
            name='member_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='messages_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expert',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expert',
            name='shield_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expert',
            name='specializations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expert',
            name='specialty',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='expert',
            name='trip_count_display',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='budget_range',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='trip',
            name='classifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trip',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='visibility',
            field=models.CharField(default='Member', max_length=40),
        ),
    ]
