from decimal import Decimal

from django.db import migrations


def seed_directory_data(apps, schema_editor):
    Expert = apps.get_model('main', 'Expert')
    Trip = apps.get_model('main', 'Trip')

    experts = {
        'Dr. Helena Vasquez': {
            'initials': 'DH',
            'profile': 'https://randomuser.me/api/portraits/women/44.jpg',
            'bio': 'Independent travel researcher with over 15 years of experience documenting sustainable tourism practices across South America and Southeast Asia. Specializes in community-based tourism assessment and ecotourism development frameworks.',
            'member_since': '2023-03-15',
            'consultancy_mode': 'Free & Paid',
            'consultation_rate': 'USD 45/session',
            'consultancy_bio': 'Available for consultations on community-based tourism planning and sustainable travel itineraries in South America and Southeast Asia.',
            'countries_visited': ['Peru', 'Colombia', 'Ecuador', 'Bolivia', 'Vietnam', 'Cambodia', 'Thailand', 'Laos', 'Indonesia', 'Malaysia'],
            'specializations': ['Community-based Tourism', 'Sustainable Tourism', 'Ecotourism', 'Cultural Tourism'],
            'specialty': 'South America & Southeast Asia',
            'shield_rating': 5,
            'profile_views': 142,
            'messages_count': 3,
            'trip_count_display': 24,
            'author_metric': 'Highest sustainability coverage',
            'is_dashboard_profile': True,
        },
        'James Worthington': {
            'initials': 'JW',
            'profile': 'https://randomuser.me/api/portraits/men/34.jpg',
            'bio': 'Former diplomatic attaché and cultural heritage consultant. Extensive travel documentation across Central Asia and the Caucasus region, with a focus on Silk Road heritage sites and traditional craftsmanship.',
            'member_since': '2022-09-10',
            'consultancy_mode': 'Paid',
            'consultation_rate': 'EUR 80/session',
            'consultancy_bio': 'Available for heritage route planning and educational travel design across the Caucasus and Central Asia.',
            'countries_visited': ['Georgia', 'Armenia', 'Azerbaijan', 'Uzbekistan', 'Kazakhstan', 'Kyrgyzstan', 'Turkey', 'Iran', 'Tajikistan'],
            'specializations': ['Heritage Tourism', 'Cultural Tourism', 'Educational Tourism'],
            'specialty': 'Central Asia & Caucasus',
            'shield_rating': 5,
            'profile_views': 96,
            'messages_count': 1,
            'trip_count_display': 18,
            'author_metric': 'Top heritage documentation',
            'is_dashboard_profile': False,
        },
        'Akiko Tanaka': {
            'initials': 'AT',
            'profile': 'https://randomuser.me/api/portraits/women/68.jpg',
            'bio': 'Gastronomy tourism specialist and culinary anthropologist. Documents food traditions, local markets, and culinary heritage across East Asia and the Mediterranean. Published author on sustainable food tourism.',
            'member_since': '2021-06-21',
            'consultancy_mode': 'Free',
            'consultation_rate': '',
            'consultancy_bio': 'Open to non-commercial conversations on culinary heritage and food tourism design.',
            'countries_visited': ['Japan', 'South Korea', 'Taiwan', 'Spain', 'Italy', 'Portugal', 'Greece', 'France', 'Singapore'],
            'specializations': ['Gastronomy Tourism', 'Cultural Tourism', 'Sustainable Tourism', 'Heritage Tourism'],
            'specialty': 'East Asia & Mediterranean',
            'shield_rating': 4,
            'profile_views': 123,
            'messages_count': 0,
            'trip_count_display': 31,
            'author_metric': 'Top gastronomy contributor',
            'is_dashboard_profile': False,
        },
        'Marcus Okafor': {
            'initials': 'MO',
            'profile': 'https://randomuser.me/api/portraits/men/52.jpg',
            'bio': 'Adventure tourism planner and wilderness guide with certifications in mountaineering and river navigation. Focuses on documenting off-grid travel routes and adventure logistics across East Africa.',
            'member_since': '2022-02-12',
            'consultancy_mode': 'No consultancy',
            'consultation_rate': '',
            'consultancy_bio': 'Not currently offering consultancy services.',
            'countries_visited': ['Kenya', 'Tanzania', 'Uganda', 'Rwanda', 'Ethiopia', 'Namibia', 'Botswana', 'Zambia'],
            'specializations': ['Adventure Tourism', 'Ecotourism', 'Sustainable Tourism', 'Rural Tourism'],
            'specialty': 'East Africa Adventure',
            'shield_rating': 5,
            'profile_views': 88,
            'messages_count': 0,
            'trip_count_display': 15,
            'author_metric': 'Top adventure fieldwork',
            'is_dashboard_profile': False,
        },
    }

    expert_objs = {}
    for name, payload in experts.items():
        expert_objs[name], _ = Expert.objects.update_or_create(name=name, defaults=payload)

    trips = [
        {
            'title': 'Tokyo & Kyoto Explorer',
            'classification': 'Cultural Tourism',
            'classifications': ['Cultural Tourism'],
            'country': 'Japan',
            'countries': ['Japan'],
            'city': 'Tokyo',
            'duration': '14 days',
            'expert': expert_objs['Akiko Tanaka'],
            'members': 12,
            'rating': 4.8,
            'price': Decimal('3200.00'),
            'budget_range': '$2,500 – $5,000',
            'date': '2024-03-01',
            'status': 'Published',
            'visibility': 'Member',
            'views': 1380,
            'icon': '🇯🇵',
            'featured': True,
            'summary': 'A structured cultural route through Tokyo and Kyoto focused on heritage, neighborhoods, and practical rail logistics.',
        },
        {
            'title': 'Inca Trail & Sacred Valley',
            'classification': 'Adventure Tourism',
            'classifications': ['Adventure Tourism', 'Cultural Tourism'],
            'country': 'Peru',
            'countries': ['Peru'],
            'city': 'Cusco',
            'duration': '10 days',
            'expert': expert_objs['Dr. Helena Vasquez'],
            'members': 8,
            'rating': 4.9,
            'price': Decimal('2800.00'),
            'budget_range': '$2,500 – $5,000',
            'date': '2024-06-01',
            'status': 'Published',
            'visibility': 'Member',
            'views': 1490,
            'icon': '🇵🇪',
            'featured': True,
            'summary': 'An adventure-focused planning record for the Inca Trail and Sacred Valley with field logistics and pacing notes.',
        },
        {
            'title': 'Fjords & Northern Lights',
            'classification': 'Nature Tourism',
            'classifications': ['Nature Tourism'],
            'country': 'Norway',
            'countries': ['Norway'],
            'city': 'Tromso',
            'duration': '8 days',
            'expert': expert_objs['James Worthington'],
            'members': 6,
            'rating': 4.7,
            'price': Decimal('4100.00'),
            'budget_range': '$2,500 – $5,000',
            'date': '2024-01-01',
            'status': 'Published',
            'visibility': 'Member',
            'views': 1170,
            'icon': '🇳🇴',
            'featured': True,
            'summary': 'A winter route through Norway oriented around fjord logistics and northern lights timing.',
        },
        {
            'title': 'Culinary Heritage Trail: Northern Spain',
            'classification': 'Gastronomy Tourism',
            'classifications': ['Gastronomy Tourism', 'Cultural Tourism'],
            'country': 'Spain',
            'countries': ['Spain'],
            'city': 'San Sebastian',
            'duration': '12 days',
            'expert': expert_objs['Akiko Tanaka'],
            'members': 14,
            'rating': 4.9,
            'price': Decimal('3600.00'),
            'budget_range': '$2,500 – $5,000',
            'date': '2024-04-12',
            'status': 'Published',
            'visibility': 'Member',
            'views': 3175,
            'icon': '🇪🇸',
            'featured': False,
            'summary': 'A ranked gastronomy route across northern Spain built around food traditions, local markets, and regional heritage.',
        },
        {
            'title': 'East African Rift Valley Expedition',
            'classification': 'Adventure Tourism',
            'classifications': ['Adventure Tourism', 'Ecotourism'],
            'country': 'Kenya',
            'countries': ['Kenya', 'Tanzania'],
            'city': 'Nairobi',
            'duration': '16 days',
            'expert': expert_objs['Marcus Okafor'],
            'members': 9,
            'rating': 4.8,
            'price': Decimal('2950.00'),
            'budget_range': '$2,500 – $5,000',
            'date': '2024-07-08',
            'status': 'Published',
            'visibility': 'Member',
            'views': 2654,
            'icon': '🌋',
            'featured': False,
            'summary': 'An expedition-style route through the Rift Valley with field-tested adventure and conservation logistics.',
        },
        {
            'title': 'Silk Road Heritage: Uzbekistan Corridor',
            'classification': 'Heritage Tourism',
            'classifications': ['Heritage Tourism', 'Cultural Tourism'],
            'country': 'Uzbekistan',
            'countries': ['Uzbekistan'],
            'city': 'Samarkand',
            'duration': '11 days',
            'expert': expert_objs['James Worthington'],
            'members': 11,
            'rating': 4.8,
            'price': Decimal('2400.00'),
            'budget_range': '$1,000 – $2,500',
            'date': '2024-05-16',
            'status': 'Published',
            'visibility': 'Member',
            'views': 2310,
            'icon': '🕌',
            'featured': False,
            'summary': 'A heritage corridor study through Uzbekistan focused on Silk Road sites and craftsmanship traditions.',
        },
        {
            'title': 'Sustainable Communities of the Peruvian Highlands',
            'classification': 'Community-based Tourism',
            'classifications': ['Community-based Tourism', 'Sustainable Tourism', 'Cultural Tourism'],
            'country': 'Peru',
            'countries': ['Peru'],
            'city': 'Cusco',
            'duration': '14 days',
            'expert': expert_objs['Dr. Helena Vasquez'],
            'members': 13,
            'rating': 4.9,
            'price': Decimal('2500.00'),
            'budget_range': '$2,500 – $5,000',
            'date': '2024-08-20',
            'status': 'Published',
            'visibility': 'Member',
            'views': 1842,
            'icon': '🏔️',
            'featured': False,
            'summary': 'A structured documentation set around highland community tourism models and sustainable travel operations.',
        },
        {
            'title': 'Mekong Delta Community Tourism Assessment',
            'classification': 'Community-based Tourism',
            'classifications': ['Community-based Tourism', 'Ecotourism', 'Cultural Tourism'],
            'country': 'Vietnam',
            'countries': ['Vietnam', 'Cambodia'],
            'city': 'Can Tho',
            'duration': '19 days',
            'expert': expert_objs['Dr. Helena Vasquez'],
            'members': 10,
            'rating': 4.7,
            'price': Decimal('1800.00'),
            'budget_range': '$1,000 – $2,500',
            'date': '2024-09-11',
            'status': 'Published',
            'visibility': 'Member',
            'views': 1520,
            'icon': '🌾',
            'featured': False,
            'summary': 'A community tourism assessment across Vietnam and Cambodia built around river systems, local operators, and ecological sensitivity.',
        },
    ]

    for trip in trips:
        title = trip.pop('title')
        Trip.objects.update_or_create(title=title, defaults=trip)


def reverse_seed_directory_data(apps, schema_editor):
    Expert = apps.get_model('main', 'Expert')
    Trip = apps.get_model('main', 'Trip')

    Trip.objects.filter(title__in=[
        'Tokyo & Kyoto Explorer',
        'Inca Trail & Sacred Valley',
        'Fjords & Northern Lights',
        'Culinary Heritage Trail: Northern Spain',
        'East African Rift Valley Expedition',
        'Silk Road Heritage: Uzbekistan Corridor',
        'Sustainable Communities of the Peruvian Highlands',
        'Mekong Delta Community Tourism Assessment',
    ]).delete()
    Expert.objects.filter(name__in=[
        'Dr. Helena Vasquez',
        'James Worthington',
        'Akiko Tanaka',
        'Marcus Okafor',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_expert_author_metric_expert_consultancy_bio_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_directory_data, reverse_seed_directory_data),
    ]