# Generated by Django 6.0.3 on 2026-03-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userengagementevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userengagementevent',
            new_name='main_useren_created_507a3d_idx',
            old_name='main_useren_created_592661_idx',
        ),
        migrations.RenameIndex(
            model_name='userengagementevent',
            new_name='main_useren_event_t_99986a_idx',
            old_name='main_useren_event_t_5021d7_idx',
        ),
    ]
